FROM python@sha256:14ab73bd56794689c00cce8162da1eb71925b188299f35f81717ec23816a5dea AS base

LABEL org.opencontainers.image.source="https://github.com/mestre8d/rathena-docker"
LABEL org.opencontainers.image.description="Contains a rAthena compilation environment in Alpine Linux"

RUN apt update -y && apt upgrade -y && pip3 install --upgrade pip && apt install build-essential cmake python3 python3-setuptools bash -y && \
    groupadd -g 1000 temp-control && useradd temp-control -u 1000 -g 1000 -m -s /bin/bash -d /app && \
    chown -R 1000:1000 /app && pip3 install setuptools

ADD https://github.com/joan2937/pigpio.git#v79 /app/pigpio

RUN cd /app/pigpio && make && make install